# note:  sheldonは定義された順序でpluginsを処理する
shell = "zsh"

# 遅延読み込み設定
# ref: https://sheldon.cli.rs/Examples.html?search=post
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

# zshファイルに記載のcompinitより前に反映
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.dotfiles-sync]
local = "~/Documents/dotfiles/.config/zsh/sync"
use = ["*.zsh"]
apply = ["source"]

[plugins.dotfiles-defer]
local = "~/Documents/dotfiles/.config/zsh/defer"
use = ["*.zsh"]
apply = ["defer"]

[plugins.minimal]
github = "subnixr/minimal"
# promptのカスタマイズ
hooks.post = '''
  MNML_INSERT_CHAR='❯'
  MNML_RPROMPT=(mnml_git mnml_datetime)

  function mnml_datetime {
    local _w="%{\e[0m%}"
    local _g="%{\e[38;5;244m%}"
    local now="$(TZ=Asia/Tokyo date +%T)"
    local ymd="$(TZ=Asia/Tokyo date +%F)"
    printf '%b' "$_g$ymd$_w $_g$now"
  }

  () {
    local emoji=('🐶' '🐱' '🐙' '🍺' '🍵' '🍣' '👻' '🌟')
    MNML_USER_CHAR=$emoji[($RANDOM % $#emoji + 1)]
  }
'''

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.zeno]
github = "yuki-yano/zeno.zsh"
use = ["zeno-plugin.zsh"]
apply = ["defer"]

# 他pluginが定義するwidget/hookをハイライトするため、最後に配置
[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
apply = ["defer"]

